apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-30s
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sleeper
          image: busybox:1.36
          command: ["sh", "-c", "sleep 30"]
